name: taskmgr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    # Existing dependencies
    - fastapi
    - uvicorn
    - sqlalchemy
    - psycopg2-binary
    - pydantic
    - python-dotenv
    - pytest
    - alembic
    - httpx
    # Frontend requirements
    - streamlit>=1.22.0
    - requests>=2.28.2
    # OpenTelemetry packages
    - opentelemetry-api
    - opentelemetry-sdk
    - opentelemetry-instrumentation-fastapi
    - opentelemetry-exporter-otlp
    - opentelemetry-instrumentation-sqlalchemy
    - pytest-opentelemetry
