version: '3'

services:
  postgres:
    container_name: taskmgr-postgres
    image: postgres:15
    environment:
      POSTGRES_USER: taskmgr
      POSTGRES_PASSWORD: taskmgr_password
      POSTGRES_DB: taskmgr_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskmgr -d taskmgr_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  otel-collector:
    container_name: taskmgr-otel-collector
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
      - "8888:8888"  # Metrics endpoint
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres_data:
